inherit_from: ~/.rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
